### ISSUE TITLE
include_top has reverse meaning

### ISSUE THREAD

**Issue by rlleshi** [shkarupa-alex/tfvan#3]
From the docs: `include_top: whether to include the fully-connected layer at the top of the network.`

However, if [True](https://github.com/shkarupa-alex/tfvan/blob/3e8d18458d3e8929fca25df255c86fb1db9f46ef/tfvan/model.py#L135), it is actually not including the layer.

**Comment by shkarupa-alex** [comment]
keras.applications.* provides 2 sets of weights: with and without head.
To mimic such behaviour and keep "include_top" flag the model always builds with head, but if include_top=False another model reslices everything from input to last non-head layer.
