### ISSUE TITLE
Double Heads

### ISSUE THREAD

**Issue by rlleshi** [shkarupa-alex/tfvan#4]
Regardless of whether you want to provide your own head or not, a head is created [here](https://github.com/shkarupa-alex/tfvan/blob/3e8d18458d3e8929fca25df255c86fb1db9f46ef/tfvan/model.py#L114). 

So in the case that you want to provide a custom one, you end up with 2x.

**Comment by shkarupa-alex** [comment]
Yes, but https://github.com/shkarupa-alex/tfvan/issues/3#issuecomment-1221849028
There should be no memory/parameter overhead in the final model
